# Compose file version
version: "3.9"

# services
services:

  l4t-tensorflow:
    image: $L4T_BASE_IMAGE
    container_name: $ML_TAG
    tty: true
    stdin_open: true
    profiles:
      - tensorflow

